version: 2
updates:
  # Terraform provider updates
  - package-ecosystem: "terraform"
    directory: "/terraform/bootstrap"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "terraform"
    directory: "/terraform/website"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
